# codemagic.yaml
workflows:
  build-flutter-ios-app:
    name: Build Flutter iOS App
    instance_type: mac_mini_m2
    max_build_duration: 90 # Increased timeout just in case

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FCI_BUILD_DIR/ios/Pods

    scripts:
      - name: Get Flutter dependencies
        script: | 
          flutter pub get
      
      - name: Prepare iOS Podfile
        script: | 
          set -e # Exit immediately if a command fails
          PODFILE_PATH="ios/Podfile"

          echo "--- Podfile before modification ---"
          cat $PODFILE_PATH
          echo "-----------------------------------"

          # Use a Ruby script to configure the Podfile for modern Firebase SDKs.
          ruby -e "
          content = File.read('$PODFILE_PATH')

          # 1. Set platform to iOS 13.0.
          content.gsub!(/# platform :ios, '11.0'/, \"platform :ios, '13.0'\")
          content.gsub!(/# platform :ios, '12.0'/, \"platform :ios, '13.0'\")

          # 2. Comment out `use_frameworks!`. This is required to fix the initial
          #    'non-modular header' errors with Firebase's Objective-C pods.
          content.gsub!(/^\s*use_frameworks!/, '# use_frameworks!')

          # 3. Add `use_modular_headers!`. This is required to fix the secondary
          #    'static library integration' error with Firebase's Swift pods.
          #    We will insert it into the main target block.
          target_line = 'target \\'Runner\\' do'
          modular_headers_line = '  use_modular_headers!'
          unless content.include?(modular_headers_line)
            content.gsub!(/#{target_line}/, \"#{target_line}\\n#{modular_headers_line}\")
          end
          
          File.write('$PODFILE_PATH', content)
          "

          echo "--- Podfile after modification ---"
          cat $PODFILE_PATH
          echo "----------------------------------"

      - name: Install CocoaPods dependencies
        script: | 
          cd ios
          # A full deintegrate and repo-update ensures a clean build from the modified Podfile.
          pod deintegrate
          pod install --repo-update

      - name: Build Flutter iOS app
        script: | 
          flutter build ios --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app