# codemagic.yaml
workflows:
  build-flutter-ios-app:
    name: Build Flutter iOS App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FCI_BUILD_DIR/ios/Pods

    scripts:
      - name: Get Flutter dependencies
        script: | 
          flutter pub get
      
      - name: Set iOS deployment target
        script: | 
          # Fixes "required a higher minimum deployment target" error
          sed -i.bak "s/# platform :ios, '12.0'/platform :ios, '13.0'/" ios/Podfile

      # --- FIX IS HERE ---
      - name: Fix non-modular header issue
        script: | 
          # This appends a post_install hook to the Podfile.
          # This hook changes the "CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"
          # build setting to YES for all Pods, which resolves the non-modular header error
          # commonly seen with Firebase plugins.
          cat <<-EOF >> ios/Podfile
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
              end
            end
          end
          EOF

      - name: Install CocoaPods dependencies
        script: | 
          cd ios
          pod install

      - name: Build Flutter iOS app
        script: | 
          flutter build ios --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app