# codemagic.yaml
workflows:
  build-flutter-ios-app:
    name: Build Flutter iOS App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FCI_BUILD_DIR/ios/Pods

    scripts:
      - name: Get Flutter dependencies
        script: | 
          flutter pub get
      
      # --- COMBINED FIX IS HERE ---
      - name: Modify Podfile for modern SDKs
        script: | 
          # 1. Set the iOS platform version to 13.0 for modern SDKs like Firebase.
          sed -i.bak "s/# platform :ios, '12.0'/platform :ios, '13.0'/" ios/Podfile

          # 2. Add fix for non-modular header issue INSIDE the existing post_install hook.
          # This finds the line 'flutter_additional_ios_build_settings(target)' and appends
          # the necessary build setting change right after it.
          sed -i.bak "/flutter_additional_ios_build_settings(target)/a \
            target.build_configurations.each do |config|\\\
              config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'\\\
            end" ios/Podfile
          
      - name: Install CocoaPods dependencies
        script: | 
          cd ios
          pod install

      - name: Build Flutter iOS app
        script: | 
          flutter build ios --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app