// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArTwDE7uRTs-jKd-bGwt0wDIepXccleio',
    appId: '1:190437215571:web:edf633ee6ff1837bdba5a6',
    messagingSenderId: '190437215571',
    projectId: 'bingusco',
    authDomain: 'bingusco.firebaseapp.com',
    storageBucket: 'bingusco.appspot.com',
    measurementId: 'G-GNZ3PDS9YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6dtMYYNJBddGkbqdGuZ5ZxSMOp1384E',
    appId: '1:190437215571:android:1ef7420776df511adba5a6',
    messagingSenderId: '190437215571',
    projectId: 'bingusco',
    storageBucket: 'bingusco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_88CznfRnDHxzdEgnH1AhhNbuBTlO4kc',
    appId: '1:190437215571:ios:5392d504143a6824dba5a6',
    messagingSenderId: '190437215571',
    projectId: 'bingusco',
    storageBucket: 'bingusco.appspot.com',
    iosBundleId: 'com.mrhdumpty.t',
  );

}